version: '3'
services:
  chain:
    build: ./
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MNEMONIC=${MNEMONIC}
    ports: ['8545:8545']
    volumes:
      - ./db:/chain/db
      - ./artifacts:/chain/artifacts
      - ./src:/chain/src
      - ./package.json:/chain/package.json
      - ./truffle.js:/chain/truffle.js
      - ./build:/chain/build
